version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8888:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    restart: unless-stopped
