version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8504:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    restart: unless-stopped


  mkdocs:
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    working_dir: /app
    build: .
    command: mkdocs serve -a 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=1
