site_name: Supply Chain Dashboard Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Graph Class: getting-started/temporal-graph.md
    - Data Retrieval: getting-started/main.md
    - Utils : getting-started/utils.md
  - API Reference:
    - API Overview: api/README.md
    - Endpoints:
      - Versions: api/endpoints/versions.md
      - Timestamp: api/endpoints/timestamp.md
      - Schema Archive: api/endpoints/schema-archive.md
      - Live Schema: api/endpoints/live-schema.md
      - Supplier Data: api/endpoints/supplier-data.md
  - Pages :
    - Main: pages/main.md
    - Business Group: pages/business_group.md
    - Product Family: pages/product_family.md
    - Product Offering: pages/product_offering.md
    - Supplier: pages/supplier.md
    - Warehouse: pages/warehouse.md
    - Facility: pages/facility.md
    - Parts: pages/parts.md
    - Structural: pages/structural.md
    - Stress Test: pages/stress.md
    - Load Test: pages/load.md
